//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras_universitarias
    {
        public Carreras_universitarias()
        {
            this.CursosXCarrera = new HashSet<CursosXCarrera>();
        }
    
        public int Id_Carrera_Univeriatria { get; set; }
        public string Nombre_Carrera { get; set; }
        public string Codigo_Carrera { get; set; }
        public int Id_Direccion_Carrera { get; set; }
    
        public virtual Direcciones_de_carrera Direcciones_de_carrera { get; set; }
        public virtual ICollection<CursosXCarrera> CursosXCarrera { get; set; }
    }
}
