//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuatrimestre_x_Sede
    {
        public int Id_Cuatrimeste_x_Sede { get; set; }
        public int Id_Cuatrimestre { get; set; }
        public int Id_Sedes_universitarias { get; set; }
        public int Numero_cuatrimestre { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre { get; set; }
        public virtual Sedes_Universitarias Sedes_Universitarias { get; set; }
    }
}
