//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public Cursos()
        {
            this.Curso_x_Cuatrimestre = new HashSet<Curso_x_Cuatrimestre>();
            this.Curso_x_Sede = new HashSet<Curso_x_Sede>();
            this.Cursos1 = new HashSet<Cursos>();
            this.CursosXCarrera = new HashSet<CursosXCarrera>();
            this.CursosXEstudiante = new HashSet<CursosXEstudiante>();
        }
    
        public int Id_Curso { get; set; }
        public string Nombre_Curso { get; set; }
        public string Codigo_Curso { get; set; }
        public Nullable<int> Codigo_Requisito { get; set; }
    
        public virtual ICollection<Curso_x_Cuatrimestre> Curso_x_Cuatrimestre { get; set; }
        public virtual ICollection<Curso_x_Sede> Curso_x_Sede { get; set; }
        public virtual ICollection<Cursos> Cursos1 { get; set; }
        public virtual Cursos Cursos2 { get; set; }
        public virtual ICollection<CursosXCarrera> CursosXCarrera { get; set; }
        public virtual ICollection<CursosXEstudiante> CursosXEstudiante { get; set; }
    }
}
