//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosxCarreraxSede
    {
        public int Id_CursosxCarreraxSede { get; set; }
        public int Id_Curso { get; set; }
        public int Id_Carrera { get; set; }
        public int Id_Sede { get; set; }
    
        public virtual Carreras_universitarias Carreras_universitarias { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Sedes_Universitarias Sedes_Universitarias { get; set; }
    }
}
