//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_x_Cuatrimestre
    {
        public int Id_Curso_x_Cuatrimestre { get; set; }
        public int Id_Curso { get; set; }
        public int Id_Num_Cuatrimestre { get; set; }
        public int Año_Cuatrimestre { get; set; }
        public int Id_Cuatrimestre { get; set; }
        public int Id_Estudiante { get; set; }
        public int Id_Sede_Universitaria { get; set; }
    
        public virtual Cuatrimestre Cuatrimestre { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Numero_Cuatrimestre Numero_Cuatrimestre { get; set; }
    }
}
