//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public Estudiantes()
        {
            this.Curso_x_Cuatrimestre = new HashSet<Curso_x_Cuatrimestre>();
            this.CursosXEstudiante = new HashSet<CursosXEstudiante>();
        }
    
        public int Id_Estudiante { get; set; }
        public string Nombre_Estudiante { get; set; }
        public string Cedula_Estudiante { get; set; }
        public int Id_Provincia { get; set; }
        public int Id_Canton { get; set; }
        public int Id_Distrito { get; set; }
        public System.DateTime Fecha_Inicio_U { get; set; }
        public string Carne { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual ICollection<Curso_x_Cuatrimestre> Curso_x_Cuatrimestre { get; set; }
        public virtual ICollection<CursosXEstudiante> CursosXEstudiante { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
