//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public Funcionarios()
        {
            this.Direcciones_de_carrera = new HashSet<Direcciones_de_carrera>();
            this.Direcciones_de_carrera1 = new HashSet<Direcciones_de_carrera>();
            this.Sedes_Universitarias = new HashSet<Sedes_Universitarias>();
        }
    
        public int Id_Funcionario { get; set; }
        public string Nombre_Funcionario { get; set; }
        public string Cedula_Funcionario { get; set; }
        public int Id_Provincia { get; set; }
        public int Id_Canton { get; set; }
        public int Id_Distrito { get; set; }
        public System.DateTime Fecha_Contratacion { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual ICollection<Direcciones_de_carrera> Direcciones_de_carrera { get; set; }
        public virtual ICollection<Direcciones_de_carrera> Direcciones_de_carrera1 { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Sedes_Universitarias> Sedes_Universitarias { get; set; }
    }
}
