//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class matriculaBDEntities : DbContext
    {
        public matriculaBDEntities()
            : base("name=matriculaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Carreras_universitarias> Carreras_universitarias { get; set; }
        public DbSet<Cuatrimestre> Cuatrimestre { get; set; }
        public DbSet<Curso_x_Cuatrimestre> Curso_x_Cuatrimestre { get; set; }
        public DbSet<Curso_x_Sede> Curso_x_Sede { get; set; }
        public DbSet<Cursos> Cursos { get; set; }
        public DbSet<CursosXCarrera> CursosXCarrera { get; set; }
        public DbSet<CursosxCarreraxSede> CursosxCarreraxSede { get; set; }
        public DbSet<CursosXEstudiante> CursosXEstudiante { get; set; }
        public DbSet<Direcciones_de_carrera> Direcciones_de_carrera { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Estudiantes> Estudiantes { get; set; }
        public DbSet<Funcionarios> Funcionarios { get; set; }
        public DbSet<Numero_Cuatrimestre> Numero_Cuatrimestre { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Sedes_Universitarias> Sedes_Universitarias { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Administadores> Administadores { get; set; }
    
        public virtual ObjectResult<Cursos_ValidarNombreCodigo_Select_Result> Cursos_ValidarNombreCodigo_Select(string nombre_Curso, string codigo_Curso)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Cursos_ValidarNombreCodigo_Select_Result>("Cursos_ValidarNombreCodigo_Select", nombre_CursoParameter, codigo_CursoParameter);
        }
    
        public virtual ObjectResult<pa_Administrador_Select_Result> pa_Administrador_Select(string nombre_Usuario, string contrasena)
        {
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Administrador_Select_Result>("pa_Administrador_Select", nombre_UsuarioParameter, contrasenaParameter);
        }
    
        public virtual int pa_Administrador_UltimaVez_Update(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Administrador_UltimaVez_Update", usuarioParameter);
        }
    
        public virtual int pa_Carreras_Delete(Nullable<int> id_Carrera)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("Id_Carrera", id_Carrera) :
                new ObjectParameter("Id_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Carreras_Delete", id_CarreraParameter);
        }
    
        public virtual int pa_Carreras_Insert(string nombre_Carrera, string codigo_Carrera, Nullable<int> iD_Direccion_Carrera)
        {
            var nombre_CarreraParameter = nombre_Carrera != null ?
                new ObjectParameter("Nombre_Carrera", nombre_Carrera) :
                new ObjectParameter("Nombre_Carrera", typeof(string));
    
            var codigo_CarreraParameter = codigo_Carrera != null ?
                new ObjectParameter("Codigo_Carrera", codigo_Carrera) :
                new ObjectParameter("Codigo_Carrera", typeof(string));
    
            var iD_Direccion_CarreraParameter = iD_Direccion_Carrera.HasValue ?
                new ObjectParameter("ID_Direccion_Carrera", iD_Direccion_Carrera) :
                new ObjectParameter("ID_Direccion_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Carreras_Insert", nombre_CarreraParameter, codigo_CarreraParameter, iD_Direccion_CarreraParameter);
        }
    
        public virtual ObjectResult<pa_Carreras_Select_Result> pa_Carreras_Select(string nombre_Carrera, string codigo_Carrera)
        {
            var nombre_CarreraParameter = nombre_Carrera != null ?
                new ObjectParameter("Nombre_Carrera", nombre_Carrera) :
                new ObjectParameter("Nombre_Carrera", typeof(string));
    
            var codigo_CarreraParameter = codigo_Carrera != null ?
                new ObjectParameter("Codigo_Carrera", codigo_Carrera) :
                new ObjectParameter("Codigo_Carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Carreras_Select_Result>("pa_Carreras_Select", nombre_CarreraParameter, codigo_CarreraParameter);
        }
    
        public virtual int pa_Carreras_Update(Nullable<int> id_Carrera_Uni, string nombre_Carrera, string codigo_Carrera, Nullable<int> id_Direccion_Carrera)
        {
            var id_Carrera_UniParameter = id_Carrera_Uni.HasValue ?
                new ObjectParameter("Id_Carrera_Uni", id_Carrera_Uni) :
                new ObjectParameter("Id_Carrera_Uni", typeof(int));
    
            var nombre_CarreraParameter = nombre_Carrera != null ?
                new ObjectParameter("Nombre_Carrera", nombre_Carrera) :
                new ObjectParameter("Nombre_Carrera", typeof(string));
    
            var codigo_CarreraParameter = codigo_Carrera != null ?
                new ObjectParameter("Codigo_Carrera", codigo_Carrera) :
                new ObjectParameter("Codigo_Carrera", typeof(string));
    
            var id_Direccion_CarreraParameter = id_Direccion_Carrera.HasValue ?
                new ObjectParameter("Id_Direccion_Carrera", id_Direccion_Carrera) :
                new ObjectParameter("Id_Direccion_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Carreras_Update", id_Carrera_UniParameter, nombre_CarreraParameter, codigo_CarreraParameter, id_Direccion_CarreraParameter);
        }
    
        public virtual ObjectResult<pa_Carreras_VerificarNombreCodigo_Select_Result> pa_Carreras_VerificarNombreCodigo_Select(string nombre_Carrera, string codigo_Carrera)
        {
            var nombre_CarreraParameter = nombre_Carrera != null ?
                new ObjectParameter("Nombre_Carrera", nombre_Carrera) :
                new ObjectParameter("Nombre_Carrera", typeof(string));
    
            var codigo_CarreraParameter = codigo_Carrera != null ?
                new ObjectParameter("Codigo_Carrera", codigo_Carrera) :
                new ObjectParameter("Codigo_Carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Carreras_VerificarNombreCodigo_Select_Result>("pa_Carreras_VerificarNombreCodigo_Select", nombre_CarreraParameter, codigo_CarreraParameter);
        }
    
        public virtual ObjectResult<pa_CarrerasNombreDireccionViewBag_Select_Result> pa_CarrerasNombreDireccionViewBag_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CarrerasNombreDireccionViewBag_Select_Result>("pa_CarrerasNombreDireccionViewBag_Select");
        }
    
        public virtual ObjectResult<pa_CarrerasRetornaSelectID_Select_Result> pa_CarrerasRetornaSelectID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CarrerasRetornaSelectID_Select_Result>("pa_CarrerasRetornaSelectID_Select");
        }
    
        public virtual ObjectResult<pa_CarrerasViewBag_Select_Result> pa_CarrerasViewBag_Select(Nullable<int> id_Carrera)
        {
            var id_CarreraParameter = id_Carrera.HasValue ?
                new ObjectParameter("Id_Carrera", id_Carrera) :
                new ObjectParameter("Id_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CarrerasViewBag_Select_Result>("pa_CarrerasViewBag_Select", id_CarreraParameter);
        }
    
        public virtual ObjectResult<pa_Cuatrimestre_Num_CuatrimiestreViewBag_Result> pa_Cuatrimestre_Num_CuatrimiestreViewBag()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cuatrimestre_Num_CuatrimiestreViewBag_Result>("pa_Cuatrimestre_Num_CuatrimiestreViewBag");
        }
    
        public virtual int pa_Curso_x_Cuatrimetre_Select(string nombre_Curso, Nullable<int> cuatrimestre)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var cuatrimestreParameter = cuatrimestre.HasValue ?
                new ObjectParameter("Cuatrimestre", cuatrimestre) :
                new ObjectParameter("Cuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Curso_x_Cuatrimetre_Select", nombre_CursoParameter, cuatrimestreParameter);
        }
    
        public virtual int pa_CursoCarrera_Delete(Nullable<int> id_Cursos_Por_Carrera)
        {
            var id_Cursos_Por_CarreraParameter = id_Cursos_Por_Carrera.HasValue ?
                new ObjectParameter("Id_Cursos_Por_Carrera", id_Cursos_Por_Carrera) :
                new ObjectParameter("Id_Cursos_Por_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CursoCarrera_Delete", id_Cursos_Por_CarreraParameter);
        }
    
        public virtual int pa_CursoCarrera_Insert(Nullable<int> iD_Curso, Nullable<int> id_Carrera_Universitaria)
        {
            var iD_CursoParameter = iD_Curso.HasValue ?
                new ObjectParameter("ID_Curso", iD_Curso) :
                new ObjectParameter("ID_Curso", typeof(int));
    
            var id_Carrera_UniversitariaParameter = id_Carrera_Universitaria.HasValue ?
                new ObjectParameter("Id_Carrera_Universitaria", id_Carrera_Universitaria) :
                new ObjectParameter("Id_Carrera_Universitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CursoCarrera_Insert", iD_CursoParameter, id_Carrera_UniversitariaParameter);
        }
    
        public virtual ObjectResult<pa_CursoCarrera_Select_Result> pa_CursoCarrera_Select(string nombre_Curso, string nombre_Carrera)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var nombre_CarreraParameter = nombre_Carrera != null ?
                new ObjectParameter("Nombre_Carrera", nombre_Carrera) :
                new ObjectParameter("Nombre_Carrera", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursoCarrera_Select_Result>("pa_CursoCarrera_Select", nombre_CursoParameter, nombre_CarreraParameter);
        }
    
        public virtual int pa_CursoCarrera_Update(Nullable<int> id_Cursos_Por_Carrera, Nullable<int> id_Curso, Nullable<int> id_Carrera_Universitaria)
        {
            var id_Cursos_Por_CarreraParameter = id_Cursos_Por_Carrera.HasValue ?
                new ObjectParameter("Id_Cursos_Por_Carrera", id_Cursos_Por_Carrera) :
                new ObjectParameter("Id_Cursos_Por_Carrera", typeof(int));
    
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("Id_Curso", id_Curso) :
                new ObjectParameter("Id_Curso", typeof(int));
    
            var id_Carrera_UniversitariaParameter = id_Carrera_Universitaria.HasValue ?
                new ObjectParameter("Id_Carrera_Universitaria", id_Carrera_Universitaria) :
                new ObjectParameter("Id_Carrera_Universitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_CursoCarrera_Update", id_Cursos_Por_CarreraParameter, id_CursoParameter, id_Carrera_UniversitariaParameter);
        }
    
        public virtual ObjectResult<pa_CursoCarreraIDS_Select_Result> pa_CursoCarreraIDS_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursoCarreraIDS_Select_Result>("pa_CursoCarreraIDS_Select");
        }
    
        public virtual ObjectResult<pa_CursoCarreraNombreDireccionViewBag_Select_Result> pa_CursoCarreraNombreDireccionViewBag_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursoCarreraNombreDireccionViewBag_Select_Result>("pa_CursoCarreraNombreDireccionViewBag_Select");
        }
    
        public virtual ObjectResult<pa_CursoCarreraRetornaID_Select_Result> pa_CursoCarreraRetornaID_Select(Nullable<int> id_Cursos_Por_Carrera)
        {
            var id_Cursos_Por_CarreraParameter = id_Cursos_Por_Carrera.HasValue ?
                new ObjectParameter("Id_Cursos_Por_Carrera", id_Cursos_Por_Carrera) :
                new ObjectParameter("Id_Cursos_Por_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursoCarreraRetornaID_Select_Result>("pa_CursoCarreraRetornaID_Select", id_Cursos_Por_CarreraParameter);
        }
    
        public virtual int pa_Cursos_Delete(Nullable<int> id_Curso)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("Id_Curso", id_Curso) :
                new ObjectParameter("Id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cursos_Delete", id_CursoParameter);
        }
    
        public virtual int pa_Cursos_Insert(string nombre_Curso, string codigo_Curso, string codigo_Requisito)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            var codigo_RequisitoParameter = codigo_Requisito != null ?
                new ObjectParameter("Codigo_Requisito", codigo_Requisito) :
                new ObjectParameter("Codigo_Requisito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cursos_Insert", nombre_CursoParameter, codigo_CursoParameter, codigo_RequisitoParameter);
        }
    
        public virtual ObjectResult<pa_Cursos_Select_Result> pa_Cursos_Select(string nombre_Curso, string codigo_Curso)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cursos_Select_Result>("pa_Cursos_Select", nombre_CursoParameter, codigo_CursoParameter);
        }
    
        public virtual int pa_Cursos_Update(Nullable<int> id_Curso, string nombre_Curso, string codigo_Curso, string codigo_Requisito)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("Id_Curso", id_Curso) :
                new ObjectParameter("Id_Curso", typeof(int));
    
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            var codigo_RequisitoParameter = codigo_Requisito != null ?
                new ObjectParameter("Codigo_Requisito", codigo_Requisito) :
                new ObjectParameter("Codigo_Requisito", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cursos_Update", id_CursoParameter, nombre_CursoParameter, codigo_CursoParameter, codigo_RequisitoParameter);
        }
    
        public virtual ObjectResult<pa_Cursos_ValidarNombreCodigo_Select_Result> pa_Cursos_ValidarNombreCodigo_Select(string nombre_Curso, string codigo_Curso)
        {
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cursos_ValidarNombreCodigo_Select_Result>("pa_Cursos_ValidarNombreCodigo_Select", nombre_CursoParameter, codigo_CursoParameter);
        }
    
        public virtual ObjectResult<pa_Cursos_x_Carrera_Select_Result> pa_Cursos_x_Carrera_Select(Nullable<int> id_Curso, string nombre_Curso, string codigo_Curso)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("Id_Curso", id_Curso) :
                new ObjectParameter("Id_Curso", typeof(int));
    
            var nombre_CursoParameter = nombre_Curso != null ?
                new ObjectParameter("Nombre_Curso", nombre_Curso) :
                new ObjectParameter("Nombre_Curso", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cursos_x_Carrera_Select_Result>("pa_Cursos_x_Carrera_Select", id_CursoParameter, nombre_CursoParameter, codigo_CursoParameter);
        }
    
        public virtual ObjectResult<pa_CursosCodigos_Select_Result> pa_CursosCodigos_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursosCodigos_Select_Result>("pa_CursosCodigos_Select");
        }
    
        public virtual ObjectResult<pa_CursosRetornaSelectID_Select_Result> pa_CursosRetornaSelectID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursosRetornaSelectID_Select_Result>("pa_CursosRetornaSelectID_Select");
        }
    
        public virtual ObjectResult<pa_CursosViewBag_Select_Result> pa_CursosViewBag_Select(Nullable<int> id_Curso)
        {
            var id_CursoParameter = id_Curso.HasValue ?
                new ObjectParameter("Id_Curso", id_Curso) :
                new ObjectParameter("Id_Curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_CursosViewBag_Select_Result>("pa_CursosViewBag_Select", id_CursoParameter);
        }
    
        public virtual int pa_Direcciones_de_Carrera_Delete(Nullable<int> id_Direccion_Carrera)
        {
            var id_Direccion_CarreraParameter = id_Direccion_Carrera.HasValue ?
                new ObjectParameter("Id_Direccion_Carrera", id_Direccion_Carrera) :
                new ObjectParameter("Id_Direccion_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Direcciones_de_Carrera_Delete", id_Direccion_CarreraParameter);
        }
    
        public virtual int pa_Direcciones_de_Carrera_Insert(string nombre_Direccion_Carrera, string codigo_Direccion_Carrera, Nullable<int> id_Director, Nullable<int> id_Subdirector)
        {
            var nombre_Direccion_CarreraParameter = nombre_Direccion_Carrera != null ?
                new ObjectParameter("Nombre_Direccion_Carrera", nombre_Direccion_Carrera) :
                new ObjectParameter("Nombre_Direccion_Carrera", typeof(string));
    
            var codigo_Direccion_CarreraParameter = codigo_Direccion_Carrera != null ?
                new ObjectParameter("Codigo_Direccion_Carrera", codigo_Direccion_Carrera) :
                new ObjectParameter("Codigo_Direccion_Carrera", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("Id_Director", id_Director) :
                new ObjectParameter("Id_Director", typeof(int));
    
            var id_SubdirectorParameter = id_Subdirector.HasValue ?
                new ObjectParameter("id_Subdirector", id_Subdirector) :
                new ObjectParameter("id_Subdirector", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Direcciones_de_Carrera_Insert", nombre_Direccion_CarreraParameter, codigo_Direccion_CarreraParameter, id_DirectorParameter, id_SubdirectorParameter);
        }
    
        public virtual ObjectResult<pa_Direcciones_de_Carrera_RetornaID_Select_Result> pa_Direcciones_de_Carrera_RetornaID_Select(Nullable<int> id_Direccion_Carrera)
        {
            var id_Direccion_CarreraParameter = id_Direccion_Carrera.HasValue ?
                new ObjectParameter("Id_Direccion_Carrera", id_Direccion_Carrera) :
                new ObjectParameter("Id_Direccion_Carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Direcciones_de_Carrera_RetornaID_Select_Result>("pa_Direcciones_de_Carrera_RetornaID_Select", id_Direccion_CarreraParameter);
        }
    
        public virtual ObjectResult<pa_Direcciones_de_Carrera_Select_Result> pa_Direcciones_de_Carrera_Select(string nombre_Direccion_Carrera, string nombre_Director)
        {
            var nombre_Direccion_CarreraParameter = nombre_Direccion_Carrera != null ?
                new ObjectParameter("Nombre_Direccion_Carrera", nombre_Direccion_Carrera) :
                new ObjectParameter("Nombre_Direccion_Carrera", typeof(string));
    
            var nombre_DirectorParameter = nombre_Director != null ?
                new ObjectParameter("Nombre_Director", nombre_Director) :
                new ObjectParameter("Nombre_Director", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Direcciones_de_Carrera_Select_Result>("pa_Direcciones_de_Carrera_Select", nombre_Direccion_CarreraParameter, nombre_DirectorParameter);
        }
    
        public virtual int pa_Direcciones_de_Carrera_Update(Nullable<int> id_Direccion_Carrera, string nombre_Direccion_Carrera, string codigo_Direccion_Carrera, Nullable<int> id_Director, Nullable<int> id_Subdirector)
        {
            var id_Direccion_CarreraParameter = id_Direccion_Carrera.HasValue ?
                new ObjectParameter("Id_Direccion_Carrera", id_Direccion_Carrera) :
                new ObjectParameter("Id_Direccion_Carrera", typeof(int));
    
            var nombre_Direccion_CarreraParameter = nombre_Direccion_Carrera != null ?
                new ObjectParameter("Nombre_Direccion_Carrera", nombre_Direccion_Carrera) :
                new ObjectParameter("Nombre_Direccion_Carrera", typeof(string));
    
            var codigo_Direccion_CarreraParameter = codigo_Direccion_Carrera != null ?
                new ObjectParameter("Codigo_Direccion_Carrera", codigo_Direccion_Carrera) :
                new ObjectParameter("Codigo_Direccion_Carrera", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("Id_Director", id_Director) :
                new ObjectParameter("Id_Director", typeof(int));
    
            var id_SubdirectorParameter = id_Subdirector.HasValue ?
                new ObjectParameter("Id_Subdirector", id_Subdirector) :
                new ObjectParameter("Id_Subdirector", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Direcciones_de_Carrera_Update", id_Direccion_CarreraParameter, nombre_Direccion_CarreraParameter, codigo_Direccion_CarreraParameter, id_DirectorParameter, id_SubdirectorParameter);
        }
    
        public virtual ObjectResult<pa_Direcciones_de_Carrera_ValidarNombreCodigo_Select_Result> pa_Direcciones_de_Carrera_ValidarNombreCodigo_Select(string nombre_Direccion, string codigo_Direccion)
        {
            var nombre_DireccionParameter = nombre_Direccion != null ?
                new ObjectParameter("Nombre_Direccion", nombre_Direccion) :
                new ObjectParameter("Nombre_Direccion", typeof(string));
    
            var codigo_DireccionParameter = codigo_Direccion != null ?
                new ObjectParameter("Codigo_Direccion", codigo_Direccion) :
                new ObjectParameter("Codigo_Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Direcciones_de_Carrera_ValidarNombreCodigo_Select_Result>("pa_Direcciones_de_Carrera_ValidarNombreCodigo_Select", nombre_DireccionParameter, codigo_DireccionParameter);
        }
    
        public virtual ObjectResult<pa_DireccionesCarrerasRetornaID_Select_Result> pa_DireccionesCarrerasRetornaID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_DireccionesCarrerasRetornaID_Select_Result>("pa_DireccionesCarrerasRetornaID_Select");
        }
    
        public virtual int pa_Estudiante_IngresarCarne_Update(string cedula_Estudiante, string carne)
        {
            var cedula_EstudianteParameter = cedula_Estudiante != null ?
                new ObjectParameter("Cedula_Estudiante", cedula_Estudiante) :
                new ObjectParameter("Cedula_Estudiante", typeof(string));
    
            var carneParameter = carne != null ?
                new ObjectParameter("Carne", carne) :
                new ObjectParameter("Carne", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Estudiante_IngresarCarne_Update", cedula_EstudianteParameter, carneParameter);
        }
    
        public virtual ObjectResult<pa_Estudiantes_Cursos_Select_Result> pa_Estudiantes_Cursos_Select(string nombre_Estudiante, string cedula_Estudiante, string codigo_Curso)
        {
            var nombre_EstudianteParameter = nombre_Estudiante != null ?
                new ObjectParameter("Nombre_Estudiante", nombre_Estudiante) :
                new ObjectParameter("Nombre_Estudiante", typeof(string));
    
            var cedula_EstudianteParameter = cedula_Estudiante != null ?
                new ObjectParameter("Cedula_Estudiante", cedula_Estudiante) :
                new ObjectParameter("Cedula_Estudiante", typeof(string));
    
            var codigo_CursoParameter = codigo_Curso != null ?
                new ObjectParameter("Codigo_Curso", codigo_Curso) :
                new ObjectParameter("Codigo_Curso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Estudiantes_Cursos_Select_Result>("pa_Estudiantes_Cursos_Select", nombre_EstudianteParameter, cedula_EstudianteParameter, codigo_CursoParameter);
        }
    
        public virtual int pa_Estudiantes_Delete(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("Id_Estudiante", id_Estudiante) :
                new ObjectParameter("Id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Estudiantes_Delete", id_EstudianteParameter);
        }
    
        public virtual int pa_Estudiantes_Insert(string nombre_Estudiante, string cedula_Estudiante, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Inicio_U, string carne)
        {
            var nombre_EstudianteParameter = nombre_Estudiante != null ?
                new ObjectParameter("Nombre_Estudiante", nombre_Estudiante) :
                new ObjectParameter("Nombre_Estudiante", typeof(string));
    
            var cedula_EstudianteParameter = cedula_Estudiante != null ?
                new ObjectParameter("Cedula_Estudiante", cedula_Estudiante) :
                new ObjectParameter("Cedula_Estudiante", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var fecha_Inicio_UParameter = fecha_Inicio_U.HasValue ?
                new ObjectParameter("Fecha_Inicio_U", fecha_Inicio_U) :
                new ObjectParameter("Fecha_Inicio_U", typeof(System.DateTime));
    
            var carneParameter = carne != null ?
                new ObjectParameter("Carne", carne) :
                new ObjectParameter("Carne", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Estudiantes_Insert", nombre_EstudianteParameter, cedula_EstudianteParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_Inicio_UParameter, carneParameter);
        }
    
        public virtual ObjectResult<pa_Estudiantes_Select_Result> pa_Estudiantes_Select(string nombre_Estudiante, string carne)
        {
            var nombre_EstudianteParameter = nombre_Estudiante != null ?
                new ObjectParameter("Nombre_Estudiante", nombre_Estudiante) :
                new ObjectParameter("Nombre_Estudiante", typeof(string));
    
            var carneParameter = carne != null ?
                new ObjectParameter("Carne", carne) :
                new ObjectParameter("Carne", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Estudiantes_Select_Result>("pa_Estudiantes_Select", nombre_EstudianteParameter, carneParameter);
        }
    
        public virtual int pa_Estudiantes_Update(Nullable<int> id_Estudiante, string nombre_Estudiante, string cedula_Estudiante, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Inicio_U, string carne)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("Id_Estudiante", id_Estudiante) :
                new ObjectParameter("Id_Estudiante", typeof(int));
    
            var nombre_EstudianteParameter = nombre_Estudiante != null ?
                new ObjectParameter("Nombre_Estudiante", nombre_Estudiante) :
                new ObjectParameter("Nombre_Estudiante", typeof(string));
    
            var cedula_EstudianteParameter = cedula_Estudiante != null ?
                new ObjectParameter("Cedula_Estudiante", cedula_Estudiante) :
                new ObjectParameter("Cedula_Estudiante", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var fecha_Inicio_UParameter = fecha_Inicio_U.HasValue ?
                new ObjectParameter("Fecha_Inicio_U", fecha_Inicio_U) :
                new ObjectParameter("Fecha_Inicio_U", typeof(System.DateTime));
    
            var carneParameter = carne != null ?
                new ObjectParameter("Carne", carne) :
                new ObjectParameter("Carne", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Estudiantes_Update", id_EstudianteParameter, nombre_EstudianteParameter, cedula_EstudianteParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_Inicio_UParameter, carneParameter);
        }
    
        public virtual ObjectResult<pa_Estudiantes_VerificarCedula_Select_Result> pa_Estudiantes_VerificarCedula_Select(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Estudiantes_VerificarCedula_Select_Result>("pa_Estudiantes_VerificarCedula_Select", cedulaParameter);
        }
    
        public virtual ObjectResult<pa_EstudiantesRetornaSelectID_Select_Result> pa_EstudiantesRetornaSelectID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_EstudiantesRetornaSelectID_Select_Result>("pa_EstudiantesRetornaSelectID_Select");
        }
    
        public virtual ObjectResult<pa_EstudiantesViewBag_Select_Result> pa_EstudiantesViewBag_Select(Nullable<int> id_Estudiante)
        {
            var id_EstudianteParameter = id_Estudiante.HasValue ?
                new ObjectParameter("Id_Estudiante", id_Estudiante) :
                new ObjectParameter("Id_Estudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_EstudiantesViewBag_Select_Result>("pa_EstudiantesViewBag_Select", id_EstudianteParameter);
        }
    
        public virtual int pa_Funcionarios_Delete(Nullable<int> iD_Funcionarios)
        {
            var iD_FuncionariosParameter = iD_Funcionarios.HasValue ?
                new ObjectParameter("ID_Funcionarios", iD_Funcionarios) :
                new ObjectParameter("ID_Funcionarios", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Funcionarios_Delete", iD_FuncionariosParameter);
        }
    
        public virtual int pa_Funcionarios_Insert(string nombre_Funcionario, string cedula_Funcionario, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Contratacion)
        {
            var nombre_FuncionarioParameter = nombre_Funcionario != null ?
                new ObjectParameter("Nombre_Funcionario", nombre_Funcionario) :
                new ObjectParameter("Nombre_Funcionario", typeof(string));
    
            var cedula_FuncionarioParameter = cedula_Funcionario != null ?
                new ObjectParameter("Cedula_Funcionario", cedula_Funcionario) :
                new ObjectParameter("Cedula_Funcionario", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var fecha_ContratacionParameter = fecha_Contratacion.HasValue ?
                new ObjectParameter("Fecha_Contratacion", fecha_Contratacion) :
                new ObjectParameter("Fecha_Contratacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Funcionarios_Insert", nombre_FuncionarioParameter, cedula_FuncionarioParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_ContratacionParameter);
        }
    
        public virtual ObjectResult<pa_Funcionarios_Select_Result> pa_Funcionarios_Select(string nombre_Funcionario, string cedula_Funcionario)
        {
            var nombre_FuncionarioParameter = nombre_Funcionario != null ?
                new ObjectParameter("Nombre_Funcionario", nombre_Funcionario) :
                new ObjectParameter("Nombre_Funcionario", typeof(string));
    
            var cedula_FuncionarioParameter = cedula_Funcionario != null ?
                new ObjectParameter("Cedula_Funcionario", cedula_Funcionario) :
                new ObjectParameter("Cedula_Funcionario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Funcionarios_Select_Result>("pa_Funcionarios_Select", nombre_FuncionarioParameter, cedula_FuncionarioParameter);
        }
    
        public virtual int pa_Funcionarios_Update(Nullable<int> id_Funcionario, string nombre_Funcionario, string cedula_Funcionario, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, Nullable<System.DateTime> fecha_Contratacion)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            var nombre_FuncionarioParameter = nombre_Funcionario != null ?
                new ObjectParameter("Nombre_Funcionario", nombre_Funcionario) :
                new ObjectParameter("Nombre_Funcionario", typeof(string));
    
            var cedula_FuncionarioParameter = cedula_Funcionario != null ?
                new ObjectParameter("Cedula_Funcionario", cedula_Funcionario) :
                new ObjectParameter("Cedula_Funcionario", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var fecha_ContratacionParameter = fecha_Contratacion.HasValue ?
                new ObjectParameter("Fecha_Contratacion", fecha_Contratacion) :
                new ObjectParameter("Fecha_Contratacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Funcionarios_Update", id_FuncionarioParameter, nombre_FuncionarioParameter, cedula_FuncionarioParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, fecha_ContratacionParameter);
        }
    
        public virtual ObjectResult<pa_Funcionarios_VerificarCedula_Select_Result> pa_Funcionarios_VerificarCedula_Select(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Funcionarios_VerificarCedula_Select_Result>("pa_Funcionarios_VerificarCedula_Select", cedulaParameter);
        }
    
        public virtual ObjectResult<pa_FuncionariosID_Select_Result> pa_FuncionariosID_Select(Nullable<int> id_Funcionario)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_FuncionariosID_Select_Result>("pa_FuncionariosID_Select", id_FuncionarioParameter);
        }
    
        public virtual ObjectResult<pa_FuncionariosRetornaSelectID_Select_Result> pa_FuncionariosRetornaSelectID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_FuncionariosRetornaSelectID_Select_Result>("pa_FuncionariosRetornaSelectID_Select");
        }
    
        public virtual ObjectResult<pa_FuncionariosViewBag_Select_Result> pa_FuncionariosViewBag_Select(Nullable<int> id_Funcionario)
        {
            var id_FuncionarioParameter = id_Funcionario.HasValue ?
                new ObjectParameter("Id_Funcionario", id_Funcionario) :
                new ObjectParameter("Id_Funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_FuncionariosViewBag_Select_Result>("pa_FuncionariosViewBag_Select", id_FuncionarioParameter);
        }
    
        public virtual ObjectResult<pa_RetornaEstudianteID_Select_Result> pa_RetornaEstudianteID_Select(string cedulaEstudianteNuevo)
        {
            var cedulaEstudianteNuevoParameter = cedulaEstudianteNuevo != null ?
                new ObjectParameter("CedulaEstudianteNuevo", cedulaEstudianteNuevo) :
                new ObjectParameter("CedulaEstudianteNuevo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_RetornaEstudianteID_Select_Result>("pa_RetornaEstudianteID_Select", cedulaEstudianteNuevoParameter);
        }
    
        public virtual int pa_Sedes_Universitarias_Delete(Nullable<int> iD_Sede_Universitaria)
        {
            var iD_Sede_UniversitariaParameter = iD_Sede_Universitaria.HasValue ?
                new ObjectParameter("ID_Sede_Universitaria", iD_Sede_Universitaria) :
                new ObjectParameter("ID_Sede_Universitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Sedes_Universitarias_Delete", iD_Sede_UniversitariaParameter);
        }
    
        public virtual ObjectResult<pa_Sedes_Universitarias_DirectorViewBag_Select_Result> pa_Sedes_Universitarias_DirectorViewBag_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_Universitarias_DirectorViewBag_Select_Result>("pa_Sedes_Universitarias_DirectorViewBag_Select");
        }
    
        public virtual int pa_Sedes_Universitarias_Insert(string nombre_Sede, string codigo_Sede, Nullable<int> id_Director, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, string direccion_Fisica)
        {
            var nombre_SedeParameter = nombre_Sede != null ?
                new ObjectParameter("Nombre_Sede", nombre_Sede) :
                new ObjectParameter("Nombre_Sede", typeof(string));
    
            var codigo_SedeParameter = codigo_Sede != null ?
                new ObjectParameter("Codigo_Sede", codigo_Sede) :
                new ObjectParameter("Codigo_Sede", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("Id_Director", id_Director) :
                new ObjectParameter("Id_Director", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var direccion_FisicaParameter = direccion_Fisica != null ?
                new ObjectParameter("Direccion_Fisica", direccion_Fisica) :
                new ObjectParameter("Direccion_Fisica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Sedes_Universitarias_Insert", nombre_SedeParameter, codigo_SedeParameter, id_DirectorParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, direccion_FisicaParameter);
        }
    
        public virtual ObjectResult<pa_Sedes_Universitarias_Select_Result> pa_Sedes_Universitarias_Select(string nombre_Sede)
        {
            var nombre_SedeParameter = nombre_Sede != null ?
                new ObjectParameter("Nombre_Sede", nombre_Sede) :
                new ObjectParameter("Nombre_Sede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_Universitarias_Select_Result>("pa_Sedes_Universitarias_Select", nombre_SedeParameter);
        }
    
        public virtual ObjectResult<pa_Sedes_Universitarias_SubdirectorViewBag_Select_Result> pa_Sedes_Universitarias_SubdirectorViewBag_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_Universitarias_SubdirectorViewBag_Select_Result>("pa_Sedes_Universitarias_SubdirectorViewBag_Select");
        }
    
        public virtual int pa_Sedes_Universitarias_Update(Nullable<int> iD_Sede_Universitaria, string nombre_Sede, string codigo_Sede, Nullable<int> id_Director, Nullable<int> id_Provincia, Nullable<int> id_Canton, Nullable<int> id_Distrito, string direccion_Fisica)
        {
            var iD_Sede_UniversitariaParameter = iD_Sede_Universitaria.HasValue ?
                new ObjectParameter("ID_Sede_Universitaria", iD_Sede_Universitaria) :
                new ObjectParameter("ID_Sede_Universitaria", typeof(int));
    
            var nombre_SedeParameter = nombre_Sede != null ?
                new ObjectParameter("Nombre_Sede", nombre_Sede) :
                new ObjectParameter("Nombre_Sede", typeof(string));
    
            var codigo_SedeParameter = codigo_Sede != null ?
                new ObjectParameter("Codigo_Sede", codigo_Sede) :
                new ObjectParameter("Codigo_Sede", typeof(string));
    
            var id_DirectorParameter = id_Director.HasValue ?
                new ObjectParameter("Id_Director", id_Director) :
                new ObjectParameter("Id_Director", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("Id_Provincia", id_Provincia) :
                new ObjectParameter("Id_Provincia", typeof(int));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("Id_Canton", id_Canton) :
                new ObjectParameter("Id_Canton", typeof(int));
    
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("Id_Distrito", id_Distrito) :
                new ObjectParameter("Id_Distrito", typeof(int));
    
            var direccion_FisicaParameter = direccion_Fisica != null ?
                new ObjectParameter("Direccion_Fisica", direccion_Fisica) :
                new ObjectParameter("Direccion_Fisica", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Sedes_Universitarias_Update", iD_Sede_UniversitariaParameter, nombre_SedeParameter, codigo_SedeParameter, id_DirectorParameter, id_ProvinciaParameter, id_CantonParameter, id_DistritoParameter, direccion_FisicaParameter);
        }
    
        public virtual ObjectResult<pa_Sedes_Universitarias_ValidarNombreCodigo_Select_Result> pa_Sedes_Universitarias_ValidarNombreCodigo_Select(string nombre_Sede, string codigo_Sede)
        {
            var nombre_SedeParameter = nombre_Sede != null ?
                new ObjectParameter("Nombre_Sede", nombre_Sede) :
                new ObjectParameter("Nombre_Sede", typeof(string));
    
            var codigo_SedeParameter = codigo_Sede != null ?
                new ObjectParameter("Codigo_Sede", codigo_Sede) :
                new ObjectParameter("Codigo_Sede", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_Universitarias_ValidarNombreCodigo_Select_Result>("pa_Sedes_Universitarias_ValidarNombreCodigo_Select", nombre_SedeParameter, codigo_SedeParameter);
        }
    
        public virtual ObjectResult<pa_Sedes_UniversitariasID_Select_Result> pa_Sedes_UniversitariasID_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_UniversitariasID_Select_Result>("pa_Sedes_UniversitariasID_Select");
        }
    
        public virtual ObjectResult<pa_Sedes_UniversitariasViewBag_Select_Result> pa_Sedes_UniversitariasViewBag_Select(Nullable<int> id_Sede)
        {
            var id_SedeParameter = id_Sede.HasValue ?
                new ObjectParameter("Id_Sede", id_Sede) :
                new ObjectParameter("Id_Sede", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Sedes_UniversitariasViewBag_Select_Result>("pa_Sedes_UniversitariasViewBag_Select", id_SedeParameter);
        }
    
        public virtual ObjectResult<RetornaCantones_Result> RetornaCantones(string nombre, Nullable<int> id_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantones_Result>("RetornaCantones", nombreParameter, id_ProvinciaParameter);
        }
    
        public virtual ObjectResult<RetornaCantonesID_Result> RetornaCantonesID(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaCantonesID_Result>("RetornaCantonesID", id_CantonParameter);
        }
    
        public virtual ObjectResult<RetornaProvincias_Result> RetornaProvincias(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaProvincias_Result>("RetornaProvincias", nombreParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_EliminaCanton(Nullable<int> id_Canton)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaCanton", id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_InsertaCanton(Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCanton", id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_ModificaCanton(Nullable<int> id_Canton, Nullable<int> id_Provincia, string nombre, Nullable<int> id_CantonInec)
        {
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            var id_ProvinciaParameter = id_Provincia.HasValue ?
                new ObjectParameter("id_Provincia", id_Provincia) :
                new ObjectParameter("id_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonInecParameter = id_CantonInec.HasValue ?
                new ObjectParameter("id_CantonInec", id_CantonInec) :
                new ObjectParameter("id_CantonInec", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaCanton", id_CantonParameter, id_ProvinciaParameter, nombreParameter, id_CantonInecParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_Result> sp_RetornaDistritos(string nombre, Nullable<int> id_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var id_CantonParameter = id_Canton.HasValue ?
                new ObjectParameter("id_Canton", id_Canton) :
                new ObjectParameter("id_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_Result>("sp_RetornaDistritos", nombreParameter, id_CantonParameter);
        }
    
        public virtual ObjectResult<sp_RetornaDistritos_ID_Result> sp_RetornaDistritos_ID(Nullable<int> id_Distrito)
        {
            var id_DistritoParameter = id_Distrito.HasValue ?
                new ObjectParameter("id_Distrito", id_Distrito) :
                new ObjectParameter("id_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RetornaDistritos_ID_Result>("sp_RetornaDistritos_ID", id_DistritoParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<pa_Cuatrimestre_VerificarCuatrimestre_Result> pa_Cuatrimestre_VerificarCuatrimestre(Nullable<int> id_Num_Cuatrimestre, Nullable<int> id_Sede_Universitaria, Nullable<int> anio_Cuatrimestre)
        {
            var id_Num_CuatrimestreParameter = id_Num_Cuatrimestre.HasValue ?
                new ObjectParameter("Id_Num_Cuatrimestre", id_Num_Cuatrimestre) :
                new ObjectParameter("Id_Num_Cuatrimestre", typeof(int));
    
            var id_Sede_UniversitariaParameter = id_Sede_Universitaria.HasValue ?
                new ObjectParameter("Id_Sede_Universitaria", id_Sede_Universitaria) :
                new ObjectParameter("Id_Sede_Universitaria", typeof(int));
    
            var anio_CuatrimestreParameter = anio_Cuatrimestre.HasValue ?
                new ObjectParameter("Anio_Cuatrimestre", anio_Cuatrimestre) :
                new ObjectParameter("Anio_Cuatrimestre", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cuatrimestre_VerificarCuatrimestre_Result>("pa_Cuatrimestre_VerificarCuatrimestre", id_Num_CuatrimestreParameter, id_Sede_UniversitariaParameter, anio_CuatrimestreParameter);
        }
    
        public virtual ObjectResult<pa_Cuatrimestre_Select_Result> pa_Cuatrimestre_Select(Nullable<int> id_Num_Cuatrimestre, Nullable<int> anio_Cuatrimestre, Nullable<int> id_Sede_Universitaria)
        {
            var id_Num_CuatrimestreParameter = id_Num_Cuatrimestre.HasValue ?
                new ObjectParameter("Id_Num_Cuatrimestre", id_Num_Cuatrimestre) :
                new ObjectParameter("Id_Num_Cuatrimestre", typeof(int));
    
            var anio_CuatrimestreParameter = anio_Cuatrimestre.HasValue ?
                new ObjectParameter("Anio_Cuatrimestre", anio_Cuatrimestre) :
                new ObjectParameter("Anio_Cuatrimestre", typeof(int));
    
            var id_Sede_UniversitariaParameter = id_Sede_Universitaria.HasValue ?
                new ObjectParameter("Id_Sede_Universitaria", id_Sede_Universitaria) :
                new ObjectParameter("Id_Sede_Universitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pa_Cuatrimestre_Select_Result>("pa_Cuatrimestre_Select", id_Num_CuatrimestreParameter, anio_CuatrimestreParameter, id_Sede_UniversitariaParameter);
        }
    
        public virtual int pa_Cuatrimestre_Insert(Nullable<int> id_Num_Cuatrimestre, Nullable<int> anio_Cuatrimestre, Nullable<int> id_Sede_Universitaria)
        {
            var id_Num_CuatrimestreParameter = id_Num_Cuatrimestre.HasValue ?
                new ObjectParameter("Id_Num_Cuatrimestre", id_Num_Cuatrimestre) :
                new ObjectParameter("Id_Num_Cuatrimestre", typeof(int));
    
            var anio_CuatrimestreParameter = anio_Cuatrimestre.HasValue ?
                new ObjectParameter("Anio_Cuatrimestre", anio_Cuatrimestre) :
                new ObjectParameter("Anio_Cuatrimestre", typeof(int));
    
            var id_Sede_UniversitariaParameter = id_Sede_Universitaria.HasValue ?
                new ObjectParameter("Id_Sede_Universitaria", id_Sede_Universitaria) :
                new ObjectParameter("Id_Sede_Universitaria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pa_Cuatrimestre_Insert", id_Num_CuatrimestreParameter, anio_CuatrimestreParameter, id_Sede_UniversitariaParameter);
        }
    }
}
