//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sedes_Universitarias
    {
        public Sedes_Universitarias()
        {
            this.Cuatrimestre = new HashSet<Cuatrimestre>();
            this.Cuatrimestre_x_Sede = new HashSet<Cuatrimestre_x_Sede>();
            this.Curso_x_Sede = new HashSet<Curso_x_Sede>();
            this.CursosxCarreraxSede = new HashSet<CursosxCarreraxSede>();
        }
    
        public int Id_Sedes_universitarias { get; set; }
        public string Nombre_Sede { get; set; }
        public string Codigo_Sede { get; set; }
        public int Id_Director { get; set; }
        public int Id_Provincia { get; set; }
        public int Id_Canton { get; set; }
        public int Id_Distrito { get; set; }
        public string Direccion_Fisica { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual ICollection<Cuatrimestre> Cuatrimestre { get; set; }
        public virtual ICollection<Cuatrimestre_x_Sede> Cuatrimestre_x_Sede { get; set; }
        public virtual ICollection<Curso_x_Sede> Curso_x_Sede { get; set; }
        public virtual ICollection<CursosxCarreraxSede> CursosxCarreraxSede { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
