//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMatricula.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vista_Sedes_Universitarias
    {
        public int Id_Sedes_universitarias { get; set; }
        public string Nombre_Sede { get; set; }
        public string Codigo_Sede { get; set; }
        public string Nombre_Funcionario { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public string Direccion_Fisica { get; set; }
    }
}
